#%RAML 1.0 Trait
headers:
  x-cms-transaction-id:
    type: string
    required: true
    minLength: 26
    maxLength: 36
    example: "hdfcv-123gghb-nbjhkn-jgfhg"
  clientId:
    type: string  
    required: true
    example: "sffhgjkvnu6578"
  clientSecret:
    type: string  
    required: true
    example: "nbjknk"